# Dependabot configuration for dependabot inspections for the repo on GitHub.

version: 2
updates:
    # Enable version updates for GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "saturday"
          time: "06:00"
      open-pull-requests-limit: 5
      commit-message:
          prefix: "ci"
          include: "scope"

    # Enable version updates for Docker
    - package-ecosystem: "docker"
      directory: "/docker"
      schedule:
          interval: "weekly"
          day: "saturday"
          time: "06:00"
      open-pull-requests-limit: 5
      commit-message:
          prefix: "docker"
          include: "scope"

    # Enable version updates for Gradle dependencies
    #
    # NOTE: Ignore org.xtclang.* dependencies as they use
    # dynamic version resolution from version.properties.
    #
    - package-ecosystem: "gradle"
      directory: "/"
      schedule:
          interval: "weekly"
          day: "saturday"
          time: "06:00"
      open-pull-requests-limit: 3
      groups:
          # Group all dependency updates into a single PR
          gradle-dependencies:
              patterns:
                  - "*"
      commit-message:
          prefix: "deps"
          include: "scope"
      ignore:
          # Ignore XDK internal dependencies
          # (use dynamic versioning)
          - dependency-name: "org.xtclang.*"
          # Ignore patch updates for build plugins (too noisy)
          - dependency-name: "*"
            update-types: ["version-update:semver-patch"]
            # But allow security updates even for patches
            # (GitHub automatically overrides this for security updates)
