#
# Action when a push event happens in our github repository.
#
# (It may be overkill, and we may want to switch to 'on: pull_request'
#  when we have tested this out enough. It is the branch developer's
#  responsibility to manually ensure the branch tests clean during
#  development and before submission as pull request)
#
# TODO: The run command could be augmented with an environment variable that
# XDK Gradle mirrors to a Gradle property, as per the convention like:
#
#  ORG_XTCLANG_BUILD_SANITY_CHECK_RUNTIME=true ./gradlew build
#
# But of course that doesn't work on Windows. Need to split though out
#
name: Build and verify Ecstasy project on push
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build --info
