name: XVM Check Push

on:
  push:

#env:
#  ORG_GRADLE_PROJECT_xtcPluginOverrideVerboseLogging: true
#  ORG_GRADLE_PROJECT_includeBuildManualTests: true
#  ORG_GRADLE_PROJECT_includeBuildAttachManualTests: true
#  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: false
#  gradle_options: --stacktrace --warning-mode all --console verbose

jobs:
  gradle-test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: .github/actions/gradle-installdist.yml
      - run: |
          echo "REUSABLE FLOW: ${{ env.gradle_options }}"
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runXtc
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runOne -PtestName=TestMisc
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runTwoTestsInSequence
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runParallel
