# TThis is here to meka sure we can trigger manual workflow dispatches.

# Everything with snapshots and gitremote seems to work. You can republish a snapshot. I guess
# the existing one should be overwritten.
# We should only publish snapshots for Master.
# Now we can use "latest.ingregration" or "latest.release" to get an updated snapshot in consumers.

name: Greeting on variable day
on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting greet_entity. Today is $DAY_OF_WEEK!"
        env:
          greet_entity: Mona
