#
# This is intended to run for every changed pushed to master.
#
# It triggers every time something is pushed to master.
# It will only build SNAPSHOT publications
# It will publish SNAPSHOT publications to the XTC Lang GitHub Maven package repository.
# It will delete older SNAPSHOT publications if we have too many of them.
# Any consumer can refer to a SNAPSHOT version, a version pattern like 'any version after this', and to 'latest.integration' to use these.
#
# On push to master - update the snapshot artifact
# We also support manual release publication, which seems can't be triggred until merge to main
# However, we will check if the current VERSION file number already exists, and warn/skip the release
# action.
#

name: XVM Publish Snapshot
on: push
env:
  ORG_GRADLE_PROJECT_xtcPluginOverrideVerboseLogging: true
jobs:
  xdk-publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      # TODO: We should just run a publish github no matter what the version is.
      # If this is a snapshot, it's working already, just do it on master only.
      # If it's a release, fail if the release exists, if not, publish the artifact, and update the VERSION file to next version + SNAPSHOT
      - uses: actions/checkout@v4
      - run: |
          echo "XDK_VERSION=$(cat ${{ github.workspace }}/VERSION)" >> "$GITHUB_ENV"
          echo "XDK_LATEST_TAG=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      - run: |
          echo "*** XDK_VERSION: ${{ env.XDK_VERSION }}"
          if [[ "$XDK_VERSION" == *SNAPSHOT ]]; then
            echo "*** XDK_VERSION is SNAPSHOT."
            echo "XDK_SNAPSHOT=1" >> "$GITHUB_ENV"
          else
            echo "*** XDK_VERSION is RELEASE."          
          fi
          echo "*** XDK_VERSION GITHUB_REF: ${{ github.ref }} ${{ github.actor }}"
          echo "*** XDK_VERSION GITHUB_REF: $GITHUB_REF $GITHUB_ACTOR"
          echo "*** XDK_VERSION_LATEST_TAG: ${{ env.XDK_LATEST_TAG }}"
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
      - uses: .github/workflows/gradle-installdist.yml
      - name: XDK Publish Snapshot to xtclang.org GitHub Maven Packages.
        if: ${{[[ "$XDK_VERSION" ] == *SNAPSHOT ]]}}
        run: echo "*** XDK_VERSION Publishing SNAPSHOT" && ./gradlew publishRemoteSnapshot
        env:
          ORG_XTCLANG_REPO_GITHUB_USER: xtclang-bot
          ORG_XTCLANG_REPO_GITHUB_TOKEN: ${{ secrets.ORG_XTCLANG_GITHUB_MAVEN_PACKAGE_REPOSITORY_READ_WRITE }}
