name: Clear all Github actions caches on sundays
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'List caches only, do not clear them.'
        required: false
        default: 'false'

jobs:
  my-job:
    name: Delete all caches, org-wide for xtclang.org/GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Purge all xtclang.org caches
        uses: easimon/wipe-cache@main
        with:
          dry-run: ${{ inputs.dry_run }}
