#
# GitHub runner workflow for building, verifying and testing the XVM repo.
#

## TODO INSTALLDIST SHOULD BE A COMMON JOB.

name: XVM Verify Push

# Check if "pull-request" makes it possible to add a branch protection status check requirement on master.
on: push

env:
  ORG_GRADLE_PROJECT_xtcPluginOverrideVerboseLogging: true
  ORG_GRADLE_PROJECT_includeBuildManualTests: true
  ORG_GRADLE_PROJECT_includeBuildAttachManualTests: true
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
  gradle_options: --stacktrace --warning-mode all --console verbose

jobs:
  verify-build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
      - run: ./gradlew ${{ env.gradle_options }} installDist
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runXtc
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runOne -PtestName=TestMisc
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runTwoTestsInSequence
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runParallel
