#
# GitHub runner workflow for building, verifying and testing the XVM repo.
#

name: Verify XDK build

# Check if "pull-request" makes it possible to add a branch protection status check requirement on master.
on: push

env:
  ORG_GRADLE_PROJECT_xtcPluginOverrideVerboseLogging: true
  ORG_GRADLE_PROJECT_includeBuildManualTests: true
  ORG_GRADLE_PROJECT_includeBuildAttachManualTests: true

  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

  workdir: $(pwd)
  gradle_options: --stacktrace --info --scan --warning-mode all --console verbose

jobs:
  verify-build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v3
      - uses: gradle/actions/setup-gradle@v3
      - run: echo ${{ env.workdir }}
      - run: ./gradlew ${{ env.gradle_options }} build
      - run: ./gradlew ${{ env.gradle_options }} installDist
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runXtc
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runOne -PtestName=TestMisc
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runTwoTestsInSequence
      - run: ./gradlew ${{ env.gradle_options }} manualTests:runParallel
